services:
  httpd:
    container_name: httpd
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro

  frontend:
    container_name: fyp-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"

  backend:
    container_name: fyp-backend
    build:
      context: ./backend
      target: builder
    
    stop_signal: SIGINT
    ports:
      - 5000:5000

  postgres:
    container_name: fyp-postgres
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=messages 

volumes:
  database_data:
    driver: local
